server:
  port: 8010

spring:
  application:
    name: user-service

  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: localhost:7001
        username: nacos
        password: nacos